In [408]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv("C:/Users/Anna/Documents/Projects/capstone/execution_data/historical_execution_data.txt")
df.head()

  V5  V6                            V7 V10 V11 V12 V13   V14  V16 V19  V21
0  1      NORMAN ELI                     1   1  19  12  1812    1   1  250
1  1      WOODS JOHN                    44   4   6   2  1814    1   1  616
2  2      GAMARRA CHARLES               13   1  19   5  1820    1   1
3  2      DESAYAS VICTORIANO             1   1  19   5  1820    1   1
4  2      NOREAGO FRANCISCO              1   1  30   5  1822    1   1  187

In [409]:
col_to_move = df.pop('V19')
df.insert(1, 'V19', col_to_move)
df.head()

  V5 V19  V6                            V7 V10 V11 V12 V13   V14  V16  V21
0  1   1      NORMAN ELI                     1   1  19  12  1812    1  250
1  1   1      WOODS JOHN                    44   4   6   2  1814    1  616
2  2   1      GAMARRA CHARLES               13   1  19   5  1820    1
3  2   1      DESAYAS VICTORIANO             1   1  19   5  1820    1
4  2   1      NOREAGO FRANCISCO              1   1  30   5  1822    1  187

In [410]:
df.columns = ['race', 'sex', 'age', 'name', 'crime_com', 'exec_method', 'date_day', 'date_month', 'date_year', 'state', 'off_occ']
df.head()

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
0,1,1,,NORMAN ELI,1,1,19,12,1812,1,250
1,1,1,,WOODS JOHN,44,4,6,2,1814,1,616
2,2,1,,GAMARRA CHARLES,13,1,19,5,1820,1,
3,2,1,,DESAYAS VICTORIANO,1,1,19,5,1820,1,
4,2,1,,NOREAGO FRANCISCO,1,1,30,5,1822,1,187

In [ ]:
# df.info()

In [ ]:
# df.dtypes

In [413]:
# df.describe shows all int data
df['off_occ'].value_counts().head(20)

off_occ
       7713
610    1749
355     586
236     370
241     348
160     226
224     197
237     169
465     163
417     131
616     119
272     111
220     106
591      93
173      76
475      69
654      68
271      63
108      56
328      51
Name: count, dtype: int64

In [ ]:
df = df.sort_values(by='date_year')
# df.head(10)

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
13062,1,1,,KENDALL GEORGE,18,4,,,1608,51,166
13063,1,1,,FRANK DANIELL,43,1,1,3,1622,51,331
13064,1,1,,CORNISH RICHARD,30,1,,,1624,51,
13065,1,1,21,HAYLE THOMAS,2,1,6,,1626,51,
5795,1,1,40,BILLINGTON JOHN,1,1,30,9,1630,25,
13066,1,2,,CHAMPION JANE,,1,,,1632,51,
13067,1,2,,HATCH MARGARET,1,1,24,6,1633,51,
5796,1,1,,WILLIAMS JOHN,10,1,,,1637,25,108
5797,1,1,,SCHOOLER WILLIAM,1,1,23,9,1637,25,297
5798,1,1,,JACKSON THOMAS,10,1,,,1638,25,

In [ ]:
df['age'] = pd.to_numeric(df['age'], errors='coerce').fillna(0).astype(int)

In [416]:
df['race'] = df['race'].replace({
    '1': 'White',
    '2': 'Black',
    '3': 'Native Am',
    '4': 'Asian-Pac-Il',
    '5': 'Hispanic',
    '6': 'Other',
    ' ': 'Unknown'
    })
df.head()

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
13062,White,1,0,KENDALL GEORGE,18,4,,,1608,51,166
13063,White,1,0,FRANK DANIELL,43,1,1,3,1622,51,331
13064,White,1,0,CORNISH RICHARD,30,1,,,1624,51,
13065,White,1,21,HAYLE THOMAS,2,1,6,,1626,51,
5795,White,1,40,BILLINGTON JOHN,1,1,30,9,1630,25,

In [417]:
df['race'].value_counts()

race
Black           7353
White           6344
Unknown          710
Native Am        362
Hispanic         349
Asian-Pac-Il     147
Other              3
Name: count, dtype: int64

In [ ]:
# df['race'].unique()
# df['sex'].unique() finally showed the "third" sex was a space

<StringArray>
['White', 'Native Am', 'Black', 'Unknown', 'Hispanic', 'Asian-Pac-Il',
 'Other']
Length: 7, dtype: str

In [ ]:
df['sex'] = df['sex'].replace({'1': 'Male', '2': 'Female', ' ': 'Unknown'})
# df.head()

In [420]:
df['sex'].value_counts()

sex
Male       14750
Female       364
Unknown      154
Name: count, dtype: int64

In [421]:
df['crime_com'] = df['crime_com'].str.strip()

In [422]:
df['crime_com'].unique()

<StringArray>
['18', '43', '30',  '2',  '1',   '', '10', '12', '31',  '9', '44', '40', '16',
  '7', '35',  '4', '36',  '8', '39', '26',  '5', '14', '33', '15', '22', '37',
 '11', '20',  '6', '23', '41', '17', '13', '19', '24', '28', '21', '27', '29',
 '25',  '3']
Length: 41, dtype: str

In [423]:
df['crime_com'] = df['crime_com'].replace({
    '1': 'Murder',
    '2': 'Rape',
    '3': 'Criminal Assault',
    '4': 'HouseBrkng-Burgl',
    '5': 'Horse Stealing',
    '6': 'Consp to Murder',
    '7': 'Treason',
    '8': 'Slave Revolt',
    '9': 'Witchcraft',
    '10': 'Robbery-Murder',
    '11': 'Rape-Murder',
    '12': 'Piracy',
    '13': 'Accessory to Mur',
    '14': 'Desertion',
    '15': 'Robbery',
    '16': 'Arson',
    '17': 'Guerilla Activity',
    '18': 'Spying-Espionage',
    '19': 'Murder-Rape-Rob',
    '20': 'Burg-Att Rape',
    '21': 'Rioting',
    '22': 'Attempted Rape',
    '23': 'Murder-Burglary',
    '24': 'Kidnap-Murder',
    '25': 'Kidnap-Murder-Rob',
    '26': 'Arson-Murder',
    '27': 'Rape-Robbery',
    '28': 'Kidnapping',
    '29': 'Prisn Brk-Kidnap',
    '30': 'Sodmy-Buggry-Bst',
    '31': 'Adultery',
    '33': 'Poisoning',
    '35': 'Concealing Birth',
    '36': 'Unspec Felony',
    '37': 'Aid Runaway Slave',
    '39': 'Counterfeiting',
    '40': 'Attempted Murder',
    '41': 'Forgery',
    '43': 'Theft-Stealing',
    '44': 'Other',
    '': 'Unknown'
})
df.head()

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
13062,White,Male,0,KENDALL GEORGE,Spying-Espionage,4,,,1608,51,166
13063,White,Male,0,FRANK DANIELL,Theft-Stealing,1,1,3,1622,51,331
13064,White,Male,0,CORNISH RICHARD,Sodmy-Buggry-Bst,1,,,1624,51,
13065,White,Male,21,HAYLE THOMAS,Rape,1,6,,1626,51,
5795,White,Male,40,BILLINGTON JOHN,Murder,1,30,9,1630,25,

In [424]:
df['crime_com'].unique()

<StringArray>
[ 'Spying-Espionage',    'Theft-Stealing',  'Sodmy-Buggry-Bst',
              'Rape',            'Murder',           'Unknown',
    'Robbery-Murder',            'Piracy',          'Adultery',
        'Witchcraft',             'Other',  'Attempted Murder',
             'Arson',           'Treason',  'Concealing Birth',
  'HouseBrkng-Burgl',     'Unspec Felony',      'Slave Revolt',
    'Counterfeiting',      'Arson-Murder',    'Horse Stealing',
         'Desertion',         'Poisoning',           'Robbery',
    'Attempted Rape', 'Aid Runaway Slave',       'Rape-Murder',
     'Burg-Att Rape',   'Consp to Murder',   'Murder-Burglary',
           'Forgery', 'Guerilla Activity',  'Accessory to Mur',
   'Murder-Rape-Rob',     'Kidnap-Murder',        'Kidnapping',
           'Rioting',      'Rape-Robbery',  'Prisn Brk-Kidnap',
 'Kidnap-Murder-Rob',  'Criminal Assault']
Length: 41, dtype: str

In [425]:
df['exec_method'].unique()
df['exec_method'] = df['exec_method'].str.strip()

In [426]:
df['exec_method'].unique()

<StringArray>
['4', '1', '15', '', '10', '6', '14', '13', '8', '11', '5', '2', '3']
Length: 13, dtype: str

In [ ]:
df['exec_method'] = df['exec_method'].replace({
    '1': 'Hanging',
    '2': 'Electrocution',
    '3': 'Asphyxiation-Gas',
    '4': 'Shot',
    '5': 'Injection',
    '6': 'Pressing',
    '8': 'Break on Wheel',
    '10': 'Burned',
    '11': 'Hung in Chains',
    '13': 'Bludgeoned',
    '14': 'Gibbetted',
    '15': 'Other',
    '': 'Unknown'
})
# df.head()

In [ ]:
# df['name'].unique()
# how to replace names that might be spaces?

In [429]:
# DON'T NEED THIS RIGHT NOW BUT COULD BE USEFUL IN FUTURE
#  df['name'] = df['name'].str.strip().str.replace(r'\s+', ' ', regex=True)

In [ ]:
# shows all info if string contains certain text in specific column
df[df['name'].str.contains('')]

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
7460,White,Male,35,KETCHUM THOMAS,Murder,Hanging,25,4,1901,NM,170

In [431]:
df['off_occ'] = df['off_occ'].str.strip().str.replace(r'\s+', ' ', regex=True)

In [432]:
df['off_occ'] = df['off_occ'].replace({
    '610': 'Slave',
    '355': 'Laborer',
    '236': 'Farm Hand',
    '241': 'Farmer',
    '160': 'Convict',
    '224': 'Ex Convict',
    '237': 'Farm Laborer',
    '465': 'Parolee',
    '417': 'Miner',
    '616': 'Soldier',
    '272': 'Gangster',
    '220': 'Escaped Convict',
    '222': 'Escaped Prisoner',
    '591': 'Seaman',
    '574': 'Sailor',
    '173': 'Criminal',
    '475': 'Pirate',
    '654': 'Tenant Farmer',
    '271': 'Gang Member',
    '108': 'Carpenter',
    '328': 'Housewife',
    '': 'Unknown'})

In [ ]:
# df['off_occ'].unique()

In [ ]:
# df['off_occ'].value_counts()

In [ ]:
# df.head()

In [450]:
# df['state'].unique()
# df['state'].dtype
df['state'] = df['state'].astype(str)
df['state'].dtype

In [451]:
df['state'] = df['state'].replace({
'1': 'AL',
'2': 'AK',
'4': 'AZ',
'5': 'AR',
'6': 'CA',
'8': 'CO',
'9': 'CT',
'10': 'DE',
'11': 'W.D.C.',
'12': 'FL',
'13': 'GA',
'15': 'HI',
'16': 'ID',
'17': 'IL',
'18': 'IN',
'19': 'IA',
'20': 'KS',
'21': 'KY',
'22': 'LA',
'23': 'ME',
'24': 'MD',
'25': 'MA',
'26': 'MI',
'27': 'MN',
'28': 'MS',
'29': 'MO',
'30': 'MT',
'31': 'NE',
'32': 'NV',
'33': 'NH',
'34': 'NJ',
'35': 'NM',
'36': 'NY',
'37': 'NC',
'38': 'ND',
'39': 'OH',
'40': 'OK',
'41': 'OR',
'42': 'PA',
'44': 'RI',
'45': 'SC',
'46': 'SD',
'47': 'TN',
'48': 'TX',
'49': 'UT',
'50': 'VT',
'51': 'VA',
'53': 'WA',
'54': 'WV',
'55': 'WI',
'56': 'WY'})

In [ ]:
# df['state'].unique()

In [453]:
df.head()

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
13062,White,Male,0,KENDALL GEORGE,Spying-Espionage,Shot,,,1608,VA,166
13063,White,Male,0,FRANK DANIELL,Theft-Stealing,Hanging,1,3,1622,VA,331
13064,White,Male,0,CORNISH RICHARD,Sodmy-Buggry-Bst,Hanging,,,1624,VA,Unknown
13065,White,Male,21,HAYLE THOMAS,Rape,Hanging,6,,1626,VA,Unknown
5795,White,Male,40,BILLINGTON JOHN,Murder,Hanging,30,9,1630,MA,Unknown

In [460]:
df[df['exec_method'] == 'Hanging']

,race,sex,age,name,crime_com,exec_method,date_day,date_month,date_year,state,off_occ
13063,White,Male,0,FRANK DANIELL,Theft-Stealing,Hanging,1,3,1622,VA,331
13064,White,Male,0,CORNISH RICHARD,Sodmy-Buggry-Bst,Hanging,,,1624,VA,Unknown
13065,White,Male,21,HAYLE THOMAS,Rape,Hanging,6,,1626,VA,Unknown
5795,White,Male,40,BILLINGTON JOHN,Murder,Hanging,30,9,1630,MA,Unknown
13066,White,Female,0,CHAMPION JANE,Unknown,Hanging,,,1632,VA,Unknown
...,...,...,...,...,...,...,...,...,...,...,...
4387,White,Male,28,HICKOCK RICHARD,Robbery-Murder,Hanging,14,4,1965,KS,Parolee
4388,White,Male,23,YORK GEORGE,Robbery-Murder,Hanging,22,6,1965,KS,Soldier
15262,White,Male,31,DODD WESTLEY ALLAN,Rape-Murder,Hanging,5,1,1993,WA,603
15263,White,Male,39,CAMPBELL CHARLES,Unknown,Hanging,27,5,1994,WA,Unknown
14710,White,Male,49,BAILEY BILLY,Murder,Hanging,25,1,1996,DE,Unknown